CREATE TABLE peoples(
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    school_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT peoples_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools (id) ON DELETE RESTRICT ON UPDATE CASCADE
);