CREATE TABLE check_ins(
    id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    people_id VARCHAR(255) NOT NULL,
    CONSTRAINT check_ins_people_id_fkey FOREIGN KEY (people_id) REFERENCES peoples (id) ON DELETE RESTRICT ON UPDATE CASCADE
);